### ISSUE TITLE
very slow when update and collecting depth data

### ISSUE THREAD

**Issue by yani-rl-ai** [griffbr/VOSVS#2]
hi @griffbr i have tried paper_vs_de.py. it is very slow when localizing the object and collect the depth information, how to solve this problem? thank you

**Comment by griffbr** [comment]
Hello @ROSNovice, 

Given the level of specificity that you provided in your message, I can only provide a couple of guesses. 1) if OSVOS is operating in CPU mode, it will take longer to process each image. 2) The HSR platform takes time to send movement commands and then receive new image data via the ROS interface. Improving hardware / ROS interface limitations is outside the scope of this work, but you are free to explore alternative interfaces for capturing images and moving HSR at the same time.

On an algorithmic level, feel free to review our paper and see if you can find ways to improve our approach. I would also recommend timing various aspects of the process to fully understand which components are taking the most time: https://stackoverflow.com/questions/5849800/what-is-the-python-equivalent-of-matlabs-tic-and-toc-functions.

Overall, it seems like the code is working for you and your HSR. This is really great! Thank you for your interest and keep up the good work.

Best,
Brent

**Comment by yani-rl-ai** [comment]
thank you for your advice. 
by the way. I found another problem. when the hand camera was very closed to the object, but the camera keeps measuring the depth and not perform the grasping. what is the main problem here?

**Comment by griffbr** [comment]
It's possible that the OSVOS segmentations are low quality and causing depth estimation errors. Have you checked these at all? One thing you can do is annotate some additional training examples from the failed segmentation images. If you retrain OSVOS using these custom training examples, the segmentation performance should improve.
